# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    session:
        enabled: true
        cookie_lifetime: 3600
        cookie_secure: false
        cookie_samesite: lax
        cookie_httponly: true
        name: PHPSESSID
        cookie_path: /
        cookie_domain: localhost
        gc_probability: 1
        gc_divisor: 100
        handler_id: session.handler.native_file
        save_path: '%kernel.cache_dir%/sessions'

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
