nelmio_cors:
    defaults:
        origin_regex: false
        allow_origin: ['http://localhost:3000']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Cookie']
        expose_headers: ['Link', 'Set-Cookie', 'X-Requested-With']
        allow_credentials: true
        max_age: 3600
    paths:
        '^/api': ~
